package config

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func (m *Manager) PrepareYAMLForPath(relPath string) (bool, map[string]string, error) {
	wantMode := m.Get("mode")
	wantTun := m.Get("tun") == "true"

	if wantTun && !m.isAdmin {
		slog.Warn("非管理员权限无法开启 TUN，已自动关闭")
		wantTun = false
		m.Set("tun", "false")
	}

	m.yamlMu.Lock()
	defer m.yamlMu.Unlock()

	var content []byte
	var err error

	if relPath != "" {
		sourcePath := filepath.Join(m.baseDir, filepath.FromSlash(relPath))
		content, err = os.ReadFile(sourcePath)
		if err != nil {
			slog.Warn("底稿文件丢失，将使用保底参数启动内核", "path", sourcePath)
			content = []byte("")
		}
	} else {
		slog.Info("当前无活跃配置，将使用保底参数启动内核")
		content = []byte("")
	}

	rawStr := strings.TrimPrefix(string(content), "\xef\xbb\xbf")
	lines := strings.Split(strings.ReplaceAll(rawStr, "\r\n", "\n"), "\n")

	outLines, extracted := processYAMLContent(lines, wantMode, wantTun)

	warningHeader := "# Auto-generated by mihomo-tray. DO NOT EDIT.\n" +
		"# Any changes will be overwritten.\n\n"

	output := warningHeader + strings.Join(outLines, "\n")
	if len(output) > 0 && !strings.HasSuffix(output, "\n") {
		output += "\n"
	}

	runtimePath := filepath.Join(m.baseDir, "config.yaml")

	if existingContent, err := os.ReadFile(runtimePath); err == nil {
		if string(existingContent) == output {
			slog.Debug("运行时配置内容无变动，已优化跳过磁盘覆盖操作", "target", "config.yaml")
			return true, extracted, nil
		}
	}

	if err := writeTmpAndRename(m.baseDir, runtimePath, []byte(output)); err != nil {
		slog.Error("写入运行时配置失败", "path", runtimePath, "err", err)
		return false, nil, fmt.Errorf("failed to save runtime yaml: %w", err)
	}

	slog.Debug("已生成运行时配置", "source", relPath, "target", "config.yaml")
	return true, extracted, nil
}

func processYAMLContent(lines []string, wantMode string, wantTun bool) ([]string, map[string]string) {
	extracted := make(map[string]string)

	var (
		hasMixedPort  bool
		mixedPortVal  string
		hasPort       bool
		portVal       string
		hasMode       bool
		hasExtCtrl    bool
		hasSecret     bool
		hasExtUI      bool
		extUIVal      string
		hasExtUIName  bool
		extUINameVal  string
		hasExtUIUrl   bool
		tunRootExists bool
		tunRootIndex  int = -1
		inTun         bool
		hasTunEnable  bool
		tunDeviceVal  string
	)

	outLines := make([]string, len(lines))
	copy(outLines, lines)

	for i, line := range outLines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "//") {
			continue
		}

		indent := 0
		prefixLen := 0
		for _, c := range line {
			if c == ' ' {
				indent++
				prefixLen++
			} else if c == '\t' {
				indent += 4
				prefixLen++
			} else {
				break
			}
		}

		if indent == 0 {
			inTun = false

			if strings.HasPrefix(trimmed, "mixed-port:") {
				hasMixedPort = true
				if parts := strings.SplitN(trimmed, ":", 2); len(parts) == 2 {
					mixedPortVal = cleanVal(parts[1])
				}
			} else if strings.HasPrefix(trimmed, "port:") {
				hasPort = true
				if parts := strings.SplitN(trimmed, ":", 2); len(parts) == 2 {
					portVal = cleanVal(parts[1])
				}
			} else if strings.HasPrefix(trimmed, "mode:") {
				hasMode = true
				comment := extractComment(line)
				outLines[i] = fmt.Sprintf("%smode: %s%s", line[:prefixLen], wantMode, comment)
			} else if strings.HasPrefix(trimmed, "external-controller:") {
				hasExtCtrl = true
			} else if strings.HasPrefix(trimmed, "secret:") {
				hasSecret = true
			} else if strings.HasPrefix(trimmed, "external-ui:") {
				hasExtUI = true
				if parts := strings.SplitN(trimmed, ":", 2); len(parts) == 2 {
					extUIVal = cleanVal(parts[1])
					if extUIVal == "" {
						comment := extractComment(line)
						outLines[i] = fmt.Sprintf("%sexternal-ui: '%s'%s", line[:prefixLen], DefaultExternalUI, comment)
						extUIVal = DefaultExternalUI
					}
				}
			} else if strings.HasPrefix(trimmed, "external-ui-name:") {
				hasExtUIName = true
				if parts := strings.SplitN(trimmed, ":", 2); len(parts) == 2 {
					extUINameVal = cleanVal(parts[1])
				}
			} else if strings.HasPrefix(trimmed, "external-ui-url:") {
				hasExtUIUrl = true
			} else if strings.HasPrefix(trimmed, "tun:") {
				tunRootExists = true
				tunRootIndex = i
				inTun = true

				if strings.Contains(trimmed, "{") && strings.Contains(trimmed, "}") {
					deviceRe := regexp.MustCompile(`device:\s*([^,}]+)`)
					if match := deviceRe.FindStringSubmatch(trimmed); len(match) > 1 {
						tunDeviceVal = cleanVal(match[1])
					}

					enableRe := regexp.MustCompile(`(?i)(enable:\s*)(true|false)`)
					if enableRe.MatchString(trimmed) {
						hasTunEnable = true
						targetEnable := fmt.Sprintf("${1}%t", wantTun)
						outLines[i] = enableRe.ReplaceAllString(line, targetEnable)
					} else {
						hasTunEnable = true
						injection := fmt.Sprintf("{enable: %t, ", wantTun)
						newTrimmed := strings.Replace(line, "{", injection, 1)
						outLines[i] = strings.Replace(newTrimmed, ", }", "}", 1)
					}
				}
			}
		} else if inTun && indent > 0 {
			if strings.HasPrefix(trimmed, "enable:") {
				hasTunEnable = true
				comment := extractComment(line)
				outLines[i] = fmt.Sprintf("%senable: %t%s", line[:prefixLen], wantTun, comment)
			} else if strings.HasPrefix(trimmed, "device:") {
				if parts := strings.SplitN(trimmed, ":", 2); len(parts) == 2 {
					tunDeviceVal = cleanVal(parts[1])
				}
			}
		}
	}

	if tunRootExists && !hasTunEnable {
		enableLine := fmt.Sprintf("  enable: %t", wantTun)
		if tunRootIndex >= 0 && tunRootIndex < len(outLines) {
			outLines = append(outLines[:tunRootIndex+1], append([]string{enableLine}, outLines[tunRootIndex+1:]...)...)
		}
	}

	if hasMixedPort {
		extracted["port"] = mixedPortVal
	} else if hasPort {
		extracted["port"] = portVal
	}
	if hasExtUIName {
		extracted["external-ui-name"] = extUINameVal
	} else {
		extracted["external-ui-name"] = ""
	}
	if tunRootExists {
		extracted["tun_device"] = tunDeviceVal
	}

	var prependLines []string

	if !hasMixedPort {
		prependLines = append(prependLines, fmt.Sprintf("mixed-port: %s", DefaultMixedPort))
		extracted["port"] = DefaultMixedPort
	}
	if !hasMode {
		modeToSet := DefaultMode
		if wantMode != "" {
			modeToSet = wantMode
		}
		prependLines = append(prependLines, "mode: "+modeToSet)
	}
	if !hasExtCtrl {
		prependLines = append(prependLines, fmt.Sprintf("external-controller: %s", DefaultExternalController))
	}
	if !hasSecret {
		prependLines = append(prependLines, fmt.Sprintf("secret: '%s'", DefaultSecret))
	}
	if !hasExtUI {
		prependLines = append(prependLines, fmt.Sprintf("external-ui: '%s'", DefaultExternalUI))
	}
	if !hasExtUIUrl {
		prependLines = append(prependLines, fmt.Sprintf("external-ui-url: '%s'", DefaultExternalUIURL))
	}
	if !tunRootExists {
		prependLines = append(prependLines, "tun:")
		prependLines = append(prependLines, fmt.Sprintf("  enable: %t", wantTun))
		extracted["tun_device"] = ""
	}

	if len(prependLines) > 0 {
		outLines = append(prependLines, outLines...)
	}

	return outLines, extracted
}

func extractComment(line string) string {
	inSingle, inDouble := false, false
	for i, char := range line {
		if char == '\'' && !inDouble {
			inSingle = !inSingle
		} else if char == '"' && !inSingle {
			inDouble = !inDouble
		} else if char == '#' && !inSingle && !inDouble {
			return " " + strings.TrimSpace(line[i:])
		}
	}
	return ""
}

func cleanVal(s string) string {
	inSingle, inDouble := false, false
	for i, char := range s {
		if char == '\'' && !inDouble {
			inSingle = !inSingle
		} else if char == '"' && !inSingle {
			inDouble = !inDouble
		} else if char == '#' && !inSingle && !inDouble {
			s = s[:i]
			break
		}
	}
	return strings.Trim(strings.TrimSpace(s), " \"'")
}

func writeTmpAndRename(baseDir, targetPath string, content []byte) error {
	targetDir := filepath.Dir(targetPath)
	_ = os.MkdirAll(targetDir, 0755)

	tmpFile, err := os.CreateTemp(targetDir, "tmp_*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmpFile.Name()

	cleaned := false
	defer func() {
		if !cleaned {
			_ = tmpFile.Close()
			_ = os.Remove(tmpName)
		}
	}()

	if _, err := tmpFile.Write(content); err != nil {
		return err
	}
	if err := tmpFile.Sync(); err != nil {
		return err
	}
	if err := tmpFile.Close(); err != nil {
		return err
	}

	cleaned = true
	return os.Rename(tmpName, targetPath)
}

func (m *Manager) ResolveKernelEndpoint(absPath string) (string, string) {
	addr := DefaultExternalController
	secret := DefaultSecret

	content, err := os.ReadFile(absPath)
	if err != nil {
		slog.Warn("提取 API 端点失败，将使用默认参数", "path", absPath)
		return addr, secret
	}

	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "external-controller:") {
			if parts := strings.SplitN(trimmed, ":", 2); len(parts) == 2 {
				addr = cleanVal(parts[1])
			}
		} else if strings.HasPrefix(trimmed, "secret:") {
			if parts := strings.SplitN(trimmed, ":", 2); len(parts) == 2 {
				secret = cleanVal(parts[1])
			}
		}
	}
	return addr, secret
}
